import type { Capability } from "@/shared/capability";

export const mockCapabilities: Capability[] = [
  {
    id: "codex:global::mock/review/SKILL.md",
    name: "review",
    provider: "codex",
    type: "skill",
    scope: "global",
    rootPath: "mock/review",
    entryPath: "mock/review/SKILL.md",
    enabled: true,
    status: "valid",
    sourceKind: "installed",
    description: "Review code changes and flag correctness risks.",
    tags: ["review"],
    lastScannedAt: "2026-04-28T00:00:00.000Z",
    validationMessages: [],
    providerMetadata: {},
  },
  {
    id: "claude:global::mock/agents/planner.md",
    name: "planner",
    provider: "claude",
    type: "agent",
    scope: "global",
    rootPath: "mock/agents/planner",
    entryPath: "mock/agents/planner.md",
    enabled: true,
    status: "needs_review",
    sourceKind: "github",
    sourceUrl: "https://github.com/example/ai-tools",
    description: "Planning agent copied from another provider.",
    tags: ["planning"],
    lastScannedAt: "2026-04-28T00:00:00.000Z",
    validationMessages: [{ level: "warning", message: "Copied across providers; review format." }],
    providerMetadata: {},
  },
  {
    id: "cursor:workspace:D:/example/workspace:D:/example/workspace/.cursor/rules/review.md",
    name: "project-review",
    provider: "cursor",
    type: "rule",
    scope: "workspace",
    workspacePath: "D:/example/workspace",
    rootPath: "D:/example/workspace/.cursor/rules",
    entryPath: "D:/example/workspace/.cursor/rules/review.md",
    enabled: true,
    status: "valid",
    sourceKind: "installed",
    description: "Project-specific Cursor review rule.",
    tags: ["workspace"],
    lastScannedAt: "2026-04-28T00:00:00.000Z",
    validationMessages: [],
    providerMetadata: {},
  },
];
